name: llm-efficiency-benchmark
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11.0
  - ipykernel
  - codecarbon
  - conda-forge::tqdm
  - conda-forge::transformers
  - huggingface_hub
  - datasets==2.16.1
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - matplotlib
  - anaconda::ipywidgets
